AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition (JSON-safe, pipeline-friendly)

Parameters:
  Family:
    Type: String
  Environment:
    Type: String

  TaskCpu:
    Type: Number
  TaskMemory:
    Type: Number

  ExecutionRoleArn:
    Type: String

  ContainerName:
    Type: String
  ContainerImage:
    Type: String
  ContainerCpu:
    Type: Number
  ContainerMemory:
    Type: Number

  ContainerPort:
    Type: Number
  HostPort:
    Type: Number

  Essential:
    Type: String
    AllowedValues: ['true','false']
    Default: 'true'

  EnvironmentVariables:
    Type: String
    Default: '[]'

  HealthCheckCommand:
    Type: String
    Default: ''

  HealthCheckInterval:
    Type: Number
    Default: 30
  HealthCheckTimeout:
    Type: Number
    Default: 5
  HealthCheckRetries:
    Type: Number
    Default: 3
  HealthCheckStartPeriod:
    Type: Number
    Default: 0

  EphemeralStorageSize:
    Type: Number
    Default: 20

Conditions:
  HasHealthCheck: !Not [!Equals [!Ref HealthCheckCommand, '']]
  HasEnvVars: !Not [!Equals [!Ref EnvironmentVariables, '[]']]
  HasCustomEphemeralStorage: !Not [!Equals [!Ref EphemeralStorageSize, 20]]

Resources:
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${Family}-${Environment}'
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Ref ExecutionRoleArn

      EphemeralStorage: !If
        - HasCustomEphemeralStorage
        - SizeInGiB: !Ref EphemeralStorageSize
        - !Ref AWS::NoValue

      ContainerDefinitions:
        - !Sub |
            {
              "name": "${ContainerName}",
              "image": "${ContainerImage}",
              "cpu": ${ContainerCpu},
              "memory": ${ContainerMemory},
              "essential": ${Essential},
              "portMappings": [
                {
                  "containerPort": ${ContainerPort},
                  "hostPort": ${HostPort},
                  "protocol": "tcp"
                }
              ],
              "environment": ${EnvironmentVariables},
              "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                  "awslogs-group": "/ecs/${Family}-${Environment}",
                  "awslogs-region": "${AWS::Region}",
                  "awslogs-stream-prefix": "ecs"
                }
              }
              ${HasHealthCheck,
                ",\"healthCheck\": {
                  \"command\": ${HealthCheckCommand},
                  \"interval\": ${HealthCheckInterval},
                  \"timeout\": ${HealthCheckTimeout},
                  \"retries\": ${HealthCheckRetries},
                  \"startPeriod\": ${HealthCheckStartPeriod}
                }",
                ""
              }
            }

Outputs:
  TaskDefinitionArn:
    Value: !Ref ECSTaskDefinition
