AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition (Type-safe, ECS compliant)

Parameters:
  Family:
    Type: String
  Environment:
    Type: String

  TaskCpu:
    Type: Number
  TaskMemory:
    Type: Number

  RequiresCompatibilities:
    Type: String
    Default: FARGATE
  NetworkMode:
    Type: String
    Default: awsvpc

  ExecutionRoleArn:
    Type: String

  ContainerName:
    Type: String
  ContainerImage:
    Type: String
  ContainerCpu:
    Type: Number
    Default: 0
  ContainerMemory:
    Type: Number

  ContainerPort:
    Type: Number
  HostPort:
    Type: Number
  Protocol:
    Type: String
    Default: tcp

  Essential:
    Type: String
    AllowedValues: ['true','false']
    Default: 'true'

  EnvironmentVariables:
    Type: String
    Default: '[]'

  HealthCheckCommand:
    Type: CommaDelimitedList
    Default: ''

  HealthCheckInterval:
    Type: Number
  HealthCheckTimeout:
    Type: Number
  HealthCheckRetries:
    Type: Number
  HealthCheckStartPeriod:
    Type: Number

  LogStreamPrefix:
    Type: String
    Default: ecs

  EphemeralStorageSize:
    Type: Number
    Default: 20

Conditions:
  HasHealthCheck: !Not [!Equals [!Join ['', !Ref HealthCheckCommand], '']]
  HasEnvVars: !Not [!Equals [!Ref EnvironmentVariables, '[]']]
  HasCustomEphemeralStorage: !Not [!Equals [!Ref EphemeralStorageSize, 20]]
  IsEssential: !Equals [!Ref Essential, 'true']

Resources:
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${Family}-${Environment}'
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      NetworkMode: !Ref NetworkMode
      RequiresCompatibilities: !Split [',', !Ref RequiresCompatibilities]
      ExecutionRoleArn: !Ref ExecutionRoleArn

      EphemeralStorage: !If
        - HasCustomEphemeralStorage
        - { SizeInGiB: !Ref EphemeralStorageSize }
        - !Ref AWS::NoValue

      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref ContainerImage
          Cpu: !Ref ContainerCpu
          Memory: !Ref ContainerMemory
          Essential: !If [IsEssential, true, false]

          PortMappings:
            - ContainerPort: !Ref ContainerPort
              HostPort: !Ref HostPort
              Protocol: !Ref Protocol

          Environment: !If
            - HasEnvVars
            - !Ref EnvironmentVariables
            - !Ref AWS::NoValue

          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/ecs/${Family}-${Environment}'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref LogStreamPrefix

          HealthCheck: !If
            - HasHealthCheck
            - {
                Command: !Ref HealthCheckCommand,
                Interval: !Ref HealthCheckInterval,
                Timeout: !Ref HealthCheckTimeout,
                Retries: !Ref HealthCheckRetries,
                StartPeriod: !Ref HealthCheckStartPeriod
              }
            - !Ref AWS::NoValue

Outputs:
  TaskDefinitionArn:
    Value: !Ref ECSTaskDefinition
