AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition (GitHub Actions compatible)

Parameters:
  Family:
    Type: String

  Environment:
    Type: String

  TaskCpu:
    Type: Number
    Default: 256

  TaskMemory:
    Type: Number
    Default: 512

  RequiresCompatibilities:
    Type: String
    Default: FARGATE

  NetworkMode:
    Type: String
    Default: awsvpc

  TaskRoleArn:
    Type: String
    Default: ''

  ExecutionRoleArn:
    Type: String
    Default: ''

  ContainerName:
    Type: String
    Default: app

  ContainerImage:
    Type: String

  ContainerCpu:
    Type: Number
    Default: 0

  ContainerMemory:
    Type: Number
    Default: 512

  Essential:
    Type: Boolean
    Default: true

  ContainerPort:
    Type: Number
    Default: 80

  HostPort:
    Type: Number
    Default: 80

  Protocol:
    Type: String
    Default: tcp

  EnvironmentVariables:
    Type: String
    Default: '[]'

  HealthCheckCommand:
    Type: CommaDelimitedList
    Default: ''

  HealthCheckInterval:
    Type: Number
    Default: 30

  HealthCheckTimeout:
    Type: Number
    Default: 5

  HealthCheckRetries:
    Type: Number
    Default: 3

  HealthCheckStartPeriod:
    Type: Number
    Default: 0

  LogDriver:
    Type: String
    Default: awslogs

  LogStreamPrefix:
    Type: String
    Default: ecs

  EphemeralStorageSize:
    Type: Number
    Default: 20

  ProjectTag:
    Type: String
    Default: ''

  CostCenterTag:
    Type: String
    Default: ''

Conditions:
  HasTaskRole: !Not [!Equals [!Ref TaskRoleArn, '']]
  HasHealthCheck: !Not [!Equals [!Join ['', !Ref HealthCheckCommand], '']]
  HasEnvVars: !Not [!Equals [!Ref EnvironmentVariables, '[]']]
  HasCustomEphemeralStorage: !Not [!Equals [!Ref EphemeralStorageSize, 20]]

Resources:
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${Family}-${Environment}'
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      RequiresCompatibilities: !Split [',', !Ref RequiresCompatibilities]
      NetworkMode: !Ref NetworkMode

      TaskRoleArn: !If [HasTaskRole, !Ref TaskRoleArn, !Ref AWS::NoValue]
      ExecutionRoleArn: !Ref ExecutionRoleArn

      EphemeralStorage: !If
        - HasCustomEphemeralStorage
        - { SizeInGiB: !Ref EphemeralStorageSize }
        - !Ref AWS::NoValue

      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref ContainerImage
          Cpu: !Ref ContainerCpu
          Memory: !Ref ContainerMemory
          Essential: !Ref Essential

          PortMappings:
            - ContainerPort: !Ref ContainerPort
              HostPort: !Ref HostPort
              Protocol: !Ref Protocol

          Environment: !If
            - HasEnvVars
            - !Ref EnvironmentVariables
            - !Ref AWS::NoValue

          LogConfiguration:
            LogDriver: !Ref LogDriver
            Options:
              awslogs-group: !Sub '/ecs/${Family}-${Environment}'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref LogStreamPrefix

          HealthCheck: !If
            - HasHealthCheck
            - {
                Command: !Ref HealthCheckCommand,
                Interval: !Ref HealthCheckInterval,
                Timeout: !Ref HealthCheckTimeout,
                Retries: !Ref HealthCheckRetries,
                StartPeriod: !Ref HealthCheckStartPeriod
              }
            - !Ref AWS::NoValue

      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
        - !If
            - ProjectTag
            - { Key: Project, Value: !Ref ProjectTag }
            - !Ref AWS::NoValue
        - !If
            - CostCenterTag
            - { Key: CostCenter, Value: !Ref CostCenterTag }
            - !Ref AWS::NoValue

Outputs:
  TaskDefinitionArn:
    Value: !Ref ECSTaskDefinition
