AWSTemplateFormatVersion: '2010-09-09'
Description: Fully parametrized ECS Task Definition with multi-container & sidecar support

################################################################################
# PARAMETERS
################################################################################
Parameters:
  Family:
    Type: String

  Environment:
    Type: String

  TaskCpu:
    Type: String
    Default: '256'

  TaskMemory:
    Type: String
    Default: '512'

  RequiresCompatibilities:
    Type: String
    Default: FARGATE

  NetworkMode:
    Type: String
    Default: awsvpc

  TaskRoleArn:
    Type: String
    Default: ''

  ExecutionRoleArn:
    Type: String
    Default: ''

  Containers:
    Type: String
    Description: JSON array of ECS containerDefinitions
    Default: '[]'

  RuntimePlatformCpuArchitecture:
    Type: String
    Default: X86_64

  RuntimePlatformOperatingSystemFamily:
    Type: String
    Default: LINUX

  EphemeralStorageSize:
    Type: Number
    Default: 0

################################################################################
# CONDITIONS
################################################################################
Conditions:
  HasTaskRole: !Not [!Equals [!Ref TaskRoleArn, '']]
  HasExecutionRole: !Not [!Equals [!Ref ExecutionRoleArn, '']]
  HasEphemeralStorage: !Not [!Equals [!Ref EphemeralStorageSize, 0]]
  HasContainers: !Not [!Equals [!Ref Containers, '[]']]

################################################################################
# RESOURCES
################################################################################
Resources:
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${Family}-${Environment}'
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      NetworkMode: !Ref NetworkMode
      RequiresCompatibilities: !Split [",", !Ref RequiresCompatibilities]

      TaskRoleArn: !If
        - HasTaskRole
        - !Ref TaskRoleArn
        - !Ref AWS::NoValue

      ExecutionRoleArn: !If
        - HasExecutionRole
        - !Ref ExecutionRoleArn
        - !Ref AWS::NoValue

      RuntimePlatform:
        CpuArchitecture: !Ref RuntimePlatformCpuArchitecture
        OperatingSystemFamily: !Ref RuntimePlatformOperatingSystemFamily

      EphemeralStorage: !If
        - HasEphemeralStorage
        - SizeInGiB: !Ref EphemeralStorageSize
        - !Ref AWS::NoValue

      ContainerDefinitions: !If
        - HasContainers
        - !FromJson !Ref Containers
        - !Ref AWS::NoValue

################################################################################
# OUTPUTS
################################################################################
Outputs:
  TaskDefinitionArn:
    Value: !Ref ECSTaskDefinition
